### ISSUE TITLE
python3 compatibility

### ISSUE THREAD

**Issue by syntonym** [gravmatt/py-term#1]
Seems to be python3 incompatible:

```
>>> import term
>>> term.right("")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/syrn/git/py-term/term.py", line 97, in right
    return ' '*(getSize()[1] - len(text)) + text
  File "/home/syrn/git/py-term/term.py", line 105, in getSize
    out = p.stdout.read().strip().split(' ')
TypeError: a bytes-like object is required, not 'str'
```

python3 compatibility would be great.

**Comment by gravmatt** [comment]
now it should be python 3 compatible 👍
